### ISSUE TITLE
Keigave emojis in je console

### ISSUE THREAD

**Issue by deannabosschert** [DanielvandeVelde/web-app-from-scratch-1920#1]
![fun fun fun](https://media.giphy.com/media/XOXdQszYm4I3m/giphy.gif)

https://github.com/DanielvandeVelde/web-app-from-scratch-1920/blob/9d694ddaf90cef121938babaa928bb195def3e88/public/js/app.js#L2

**Comment by DanielvandeVelde** [comment]
Haha thanks.
Een wat meer persoonlijke touch in de saaie code
