### ISSUE TITLE
Code flow

### ISSUE THREAD

**Issue by joostf** [DanielvandeVelde/web-app-from-scratch-1920#11]
https://github.com/DanielvandeVelde/web-app-from-scratch-1920/blob/9d694ddaf90cef121938babaa928bb195def3e88/public/js/app.js#L147

When using function declarations, it might be nice to call the functions at the top of your code. Telling the 'story' there and reference functions when needed

**Comment by DanielvandeVelde** [comment]
That sounds reasonable.
Currently breaking the code up into modules but will structure my code like a 'story' so it makes sense when being read top to bottom.
