### ISSUE TITLE
Readme

### ISSUE THREAD

**Issue by deannabosschert** [DanielvandeVelde/web-app-from-scratch-1920#12]
Add the following dingen: 
- ## Installation

```bash
git clone https://github.com/DanielvandeVelde/web-app-from-scratch-1920.git
```

- ## Data
What data cleaning do you gebruiken?

- ## Sources
Voeg je bronnen toe

- ## Rubric
Add rubric en beoordeel jezelf zodat ze bij de beoordeling kunnen seen where your webapp is at.

![lmao](https://i.imgur.com/7jGz7cm.gif)

**Comment by DanielvandeVelde** [comment]
Fixed in next commit :-)
