### ISSUE TITLE
Import css-reset in css-file

### ISSUE THREAD

**Issue by deannabosschert** [DanielvandeVelde/web-app-from-scratch-1920#2]
https://github.com/DanielvandeVelde/web-app-from-scratch-1920/blob/9d694ddaf90cef121938babaa928bb195def3e88/index.html#L9

Kun je dit niet beter importeren in je css-file?:
` @import url("base.css"); `

![css gif](https://media.giphy.com/media/13FrpeVH09Zrb2/giphy.gif)

**Comment by DanielvandeVelde** [comment]
Very smart. Consider it done.
