### ISSUE TITLE
Import font in css-file

### ISSUE THREAD

**Issue by deannabosschert** [DanielvandeVelde/web-app-from-scratch-1920#3]
Dit kun je ook importen in je css-file

https://github.com/DanielvandeVelde/web-app-from-scratch-1920/blob/9d694ddaf90cef121938babaa928bb195def3e88/index.html#L6

`@font-face {
  font-family: myFirstFont;
  src: url(sansation_light.woff);
}`

![Roboto](https://media.giphy.com/media/tczJoRU7XwBS8/giphy.gif)

**Comment by DanielvandeVelde** [comment]
Made those changes. My css skill is lacking
