### ISSUE TITLE
Add node_modules just in case

### ISSUE THREAD

**Issue by deannabosschert** [DanielvandeVelde/web-app-from-scratch-1920#4]
Maak er anders een gewoonte van om node_modules te includen lol

https://github.com/DanielvandeVelde/web-app-from-scratch-1920/blob/9d694ddaf90cef121938babaa928bb195def3e88/.gitignore#L1

![just in case](https://tenor.com/Sz52.gif)

**Comment by DanielvandeVelde** [comment]
Is ook een goed plan,
Ik was gewoon net iets te lui om een node_modules folder aan te maken en deze stond er toch al in :-)
