### ISSUE TITLE
Arrowfunctions/anonymous functions

### ISSUE THREAD

**Issue by deannabosschert** [DanielvandeVelde/web-app-from-scratch-1920#6]
Je gebruikt uitgeschreven anonieme functies/arrowfunctions door elkaar

https://github.com/DanielvandeVelde/web-app-from-scratch-1920/blob/9d694ddaf90cef121938babaa928bb195def3e88/public/js/app.js#L18

https://github.com/DanielvandeVelde/web-app-from-scratch-1920/blob/9d694ddaf90cef121938babaa928bb195def3e88/public/js/app.js#L27

![pick one](https://media.giphy.com/media/OvDTq5V3EepBS/giphy.gif)

**Comment by DanielvandeVelde** [comment]
Making use of only arrowfunctions now.
Thanks for pointing it out :-)
