### ISSUE TITLE
for loop

### ISSUE THREAD

**Issue by MonikaaS** [DanielvandeVelde/web-app-from-scratch-1920#8]
Je gebruikt eerst een forEach en hier gebruik je dan weer een for loop:

https://github.com/DanielvandeVelde/web-app-from-scratch-1920/blob/9d694ddaf90cef121938babaa928bb195def3e88/public/js/app.js#L103

Kan denk ik ook in een foreach 🤷‍♀️

**Comment by DanielvandeVelde** [comment]
Changed most to a .map() and that one to a ForEach :-)

**Comment by DanielvandeVelde** [comment]
Thank you by the way! Really helps
