### ISSUE TITLE
Breakup url in separate chunks

### ISSUE THREAD

**Issue by joostf** [DanielvandeVelde/web-app-from-scratch-1920#9]
https://github.com/DanielvandeVelde/web-app-from-scratch-1920/blob/9d694ddaf90cef121938babaa928bb195def3e88/public/js/app.js#L16

https://github.com/cmda-minor-web/best-practices/blob/master/javascript.md#split-fetch-url-in-separate-chunks

**Comment by DanielvandeVelde** [comment]
Split it into seperate chunks.
Thanks for linking all other best practices too, will review my code with all of those a bit later on :-)
